filebeat.inputs:

  - type: log
    enabled: true
    paths:
      - /path_to_logs/*.log
    json:
      keys_under_root: true
      overwrite_keys: true
      message_key: 'message'

output.elasticsearch:
  hosts: [elasticsearch_endpoint]

processors:
  - decode_json_fields:
      fields: ['message']
      target: json
